### ISSUE TITLE
Go to Definition across files

### ISSUE THREAD

**Issue by pierogitus** [Microsoft/monaco-typescript#2]
I'm using the editor with multiple TypeScript files in memory. The Go to Definition command fails when the item is in a different file than the one open in the editor.  

> TypeError: Cannot read property 'getControl' of null
    at goToDeclaration.ts:140
    at CompletePromise_ctor.CompletePromise_then [as then] (winjs.base.raw.js:1566)
    at GoToDefinitionAction.DefinitionAction._openReference (goToDeclaration.ts:139)
    at GoToDefinitionAction.DefinitionAction._onResult (goToDeclaration.ts:129)
    at goToDeclaration.ts:115
    at Object.notifySuccess [as _notify] (winjs.base.raw.js:1170)
    at Object.enter (winjs.base.raw.js:852)
    at Promise_ctor._run (winjs.base.raw.js:1068)
    at Promise_ctor._completed (winjs.base.raw.js:1036)
    at argDone (winjs.base.raw.js:1813)
errors.ts:38 Uncaught Error: Cannot read property 'getControl' of null

> TypeError: Cannot read property 'getControl' of null
    at https://npmcdn.com/monaco-editor@0.4.0/dev/vs/editor/editor.main.js:79739:30
    at CompletePromise_ctor.CompletePromise_then [as then] (https://npmcdn.com/monaco-editor@0.4.0/dev/vs/editor/editor.main.js:6941:49)
    at GoToDefinitionAction.DefinitionAction._openReference (https://npmcdn.com/monaco-editor@0.4.0/dev/vs/editor/editor.main.js:79738:113)
    at GoToDefinitionAction.DefinitionAction._onResult (https://npmcdn.com/monaco-editor@0.4.0/dev/vs/editor/editor.main.js:79729:22)
    at https://npmcdn.com/monaco-editor@0.4.0/dev/vs/editor/editor.main.js:79715:30
    at Object.notifySuccess [as _notify] (https://npmcdn.com/monaco-editor@0.4.0/dev/vs/editor/editor.main.js:6545:59)
    at Object.enter (https://npmcdn.com/monaco-editor@0.4.0/dev/vs/editor/editor.main.js:6227:30)
    at Promise_ctor._run (https://npmcdn.com/monaco-editor@0.4.0/dev/vs/editor/editor.main.js:6443:29)
    at Promise_ctor._completed (https://npmcdn.com/monaco-editor@0.4.0/dev/vs/editor/editor.main.js:6411:18)
    at argDone (https://npmcdn.com/monaco-editor@0.4.0/dev/vs/editor/editor.main.js:7188:37)

Digging into the source this function seems problematic. It just returns null so I don't see how it can find the other model. https://github.com/Microsoft/vscode/blob/master/src/vs/editor/browser/standalone/simpleServices.ts

```
private findModel(editor:editorCommon.ICommonCodeEditor, data:IResourceInput): editorCommon.IModel {
	var model = editor.getModel();
	if(model.uri.toString() !== data.resource.toString()) {
		return null;
	}

	return model;
}
```

**Comment by jrieken** [comment]
We can fix the exception but to get the feature of cross file navigation working you would need to go deeper and trade in a different service.

**Comment by pierogitus** [comment]
So is this on the roadmap or are you suggesting I need to fork?

**Comment by jrieken** [comment]
The individual services aren't exposed in the API but the create method should already today allow you to pass in services that override the [default services](https://github.com/Microsoft/vscode/blob/joh/menus/src/vs/editor/browser/standalone/standaloneEditor.ts#L54). 

Something like this `create(domNode, options, { editorService: MyOwnImplementation })` should work. Make sure to extend the [`SimpleEditorService`](https://github.com/Microsoft/vscode/blob/joh/menus/src/vs/editor/browser/standalone/simpleServices.ts#L76) or implement [`IEditorService`](https://github.com/Microsoft/vscode/blob/joh/menus/src/vs/platform/editor/common/editor.ts#L15).

**Comment by pierogitus** [comment]
Ok I see, thanks. 
On a side note its still difficult when using the bundled version on NPM because those things to extend aren't exposed. I was able to monkey patch it by hooking into the loader at runtime.
